[font]
size = 11.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

#[schemes.colors.primary]
#background = "#1a1b26"
#foreground = "#a9b1d6"

#[schemes.tokyo-night.primary]
#background = "#1a1b26"
#foreground = "#a9b1d6"

[scrolling]
history = 50000

[window]
opacity = 0.8

[window.dimensions]
columns = 87
lines = 30
